send_cli:
  name: Send CLI command
  description: Send a CLI command to the connected Flipper Zero
  fields:
    command:
      name: Command
      description: Flipper CLI command
      example: "info device"
